# Zen of Python(clean python)
zeroth = "easy to reading"
firs = "4 space for indentation"
second = "using linter(checking working thing by ruff(ruff check . --fix))\
and formatter(ckecking visibles things by black(black .))"
third = "meaningful names"
fourth = "single responsibility(one function = one responsibility)"
fifth = "testing codes"
sixth = "resulting by dicts(json), print just for debugs"
seventh = "use loggin instead of print"
eighth = "handle errors properly"
ninth = "more information by type hints(showing classes) and docstring(#notes)"
tenth = "lock every library in requirements.txt to last version until now(example:FasAPI==0.115.4)"
eleventh = "single source of truth(use env/config)"
twelvth = "modularization(clean priority)"
thirteen = "high quality and small number of comments"
fourteen = "code review and continuous integration by merging, no pushing main"
